### ISSUE TITLE
Vite Support

### ISSUE THREAD

**Issue by indifferentghost** [dannyhw/react-native-web-tailwind-repro#1]
Do you think this repo could handle throwing in vite for faster load times?
I'm hoping to build a template repo for components.

**Comment by dannyhw** [comment]
Hey well this was actually intended just to reproduce a problem with something on the styling addon so it's not the right repo for that. 

However vite support for react-native-web storybook is something I have planned. Its just going to take me a little while to get to it. Maybe next month 😅.

**Comment by indifferentghost** [comment]
This repo has helped more than you know :sweat_smile:.
Looking forward to the vite support.
